apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.name" . }}-html
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html>
      <head><title>lab10</title></head>
      <body style="font-family: system-ui; padding: 2rem">
        <h1>lab10 — nginx + Postgres on Longhorn</h1>
        <p>Deployed via ArgoCD apps-of-apps.</p>
      </body>
    </html>
